# Generated by Django 6.1.1 on 2026-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('ph', models.FloatField()),
                ('nutrient_level', models.FloatField()),
                ('fermentation_time', models.FloatField()),
                ('initial_yeast_amount', models.FloatField()),
                ('final_yield', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
